function ChangeLanguage() {
    language = document.getElementById("Language").value;
    var TextArr = [
    ["Legacy Parts Characterization", "Eski Parça Karakterizasyonu"],
    ["New Part Characterization","Yeni Parça Karakterizasyonu"],
    ["Visualization","Görselleştirme"],
    ["Molding Sheet","Proses Ayar Fişi"],
    ["Preview","Ön izleme"],
    ["Feedback","Geri bildirim"],
    ["<i class='fas fa-cubes icon'></i> Legacy Parts","<i class='fas fa-cubes icon'></i> Eski Parçalar"],
    ["<i class='fas fa-cube icon'></i> New Part","<i class='fas fa-cube icon'></i> Yeni Parça"],
    ["<i class='fas fa-chart-line icon'></i> Visualization","<i class='fas fa-chart-line icon'></i> Görselleştirme"],
    ["<i class='fas fa-list-check icon'></i> Molding Sheet","<i class='fas fa-list-check icon'></i> Proses Ayar Fişi"],
    ["<i class='fas fa-magnifying-glass icon'></i> Preview","<i class='fas fa-magnifying-glass icon'></i> Ön izleme"],
    ["<i class='fas fa-message icon'></i> Feedback","<i class='fas fa-message icon'></i> Geri bildirim"],
    ["Details","Detaylar"],
    ["Details","Detaylar"],
    ["Details","Detaylar"],
    ["Details","Detaylar"],
    ["Warning","Uyarı"],
    ["Enter process parameters, material, part and mold design information of old parts similiar to your current project. You can fill in up to 5 old parts, but a minimum of 5 parts is recommended. Click the button below the table to create the required CSV (you can check the created CSV in a following section).","Eski projelerinizin arasından yeni projenize benzer parçaların proses parametreleri, malzeme, parça ve kalıp tasarım bilgilerini girin. 5 adet eski parçaya kadar doldurabilirsiniz bununla beraber sağlıklı sonuç alabilmek için en az 3 adet benzer proje bilgisini girmeniz şiddetle önerilir. Tabloyu doldurduktan sonra tablonun altında yer alan düğmeyi tıklayarak gerekli CSV dosyasını oluşturun. (Oluşturulan CSV'yi sonraki bölümde kontrol edebilirsiniz)"],
    ["Enter part and mold design as well as material information of your current project for which you would like to predict process settings. Afterwards, click the button below to create an array of your input (you can check the created array in a following section).","Proses ayar fişini oluşturmak istediğiniz parçanızın kalıp ve ürün tasarım bilgileri ile malzeme bilgilerini girin. Ardından tablonun altındaki düğmeyi tıklayarak girdi dizisini oluşturun. (Oluşturulan diziyi sonraki bölümde kontrol edebilirsiniz)"],
    ["Click the button to create a 3D scatter plot of your new and old parts. Your old parts will appear in shades of blue and the new part will be light red. This plot visually indicates which old part is closest and most similiar to your current project.","Aşağıdaki düğmeyi tıklayarak eski ve yeni parçalarınızın 3D serpme diyagramını oluşturun. Eski parçalarınız kırmızı yeni parçanız ise gri görünecektir.Bu diyagram eski parçalarınızdan hangisinin yeni parçanıza en yakın olduğunu gösterecektir."],
    ["Please ensure that the gray point is surrounded by white points. While you can still use the service if the gray dot is an outlier, predicition accuracy can drastically decrease. Therefore it is recommended to enter different old parts, re-create the CSV and the plot until the gray dot is in the center.","Lütfen gri noktaların beyaz noktalarla çevrili olduğundan emin olun. Eğer gri nokta çizgi dışında ise sonucun tutarlılık oranı önemli oranda düşecektir bu nedenle başka eski parçalarınızın verilerini girerek CSV dosyasını tekrar oluşturun, bu döngüyü gri nokta merkeze gelene kadar tekrarlayın."],
    ["Please find below your created old parts CSV and new part array. You need to add your e-mail address and agree to the general terms and conditions in order to receive your molding sheet. Submit all information and receive the molding sheet.","Oluşturduğunuz CSV ve yeni parça dizisi aşağıdadır. Proses ayar fişinizi almak için e-posta adresinizi eklemeniz ve genel şartları ve koşulları kabul etmeniz gerekir. Tüm bilgileri gönderin ve proses ayar fişinizi alın"],
    ["For your convenience, you can copy and save the old part CSV to re-use it for your next predicition, but it is recommended to use different, more similiar parts to the most current project per predicition.","Oluşturduğunuz CSV'yi diğer projelerinizde kullanmak üzere kopyalayabilirsiniz fakat daha gerçekci sonuçlar elde edebilmek adına her projenizde o projeye en çok benzeyen parçaların verilerini girmeniz önerilir."],
    ["Your data will immediately be processed upon submission. It can take up to 5 minutes for the preview to be shown. Do not refresh your browser, it will update automatically. In the meantime, you will receive a copy of your molding sheet via e-mail. Please check your inbox.","Verileriniz gönderildikten hemen sonra işlenmeye başlanacaktır. Sonuçların gösterilmesi 5 dakika kadar sürebilir. Tarayıcınızı yenilemeyin, otomatik olarak güncellenir. Bu arada, proses ayar fişinizin bir kopyasını e-posta yoluyla alacaksınız. Lütfen gelen kutunuzu kontrol edin."],
    ["Create Legacy Parts CSV","Eski Parçalar için CSV Oluştur"],
    ["Create New Part Array","Yeni Parça Dizisi Oluştur"],
    ["(Re-)Plot Parts","Diyagramı Oluştur"],
    ["Submit","Gönder"],
    ["Legacy Part 1","Eski Parça 1"],
    ["Legacy Part 2","Eski Parça 2"],
    ["Legacy Part 3","Eski Parça 3"],
    ["Legacy Part 4","Eski Parça 4"],
    ["Legacy Part 5","Eski Para 5"],
    ["Part and mold design","Parça ve Kalıp Tasarımı"],
    ["Min. Wall Thickness [mm]","Min. Et Kalınlığı [mm]"],
    ["Avg. Wall Thickness [mm]","Ort. Et Kalınlığı [mm]"],
    ["Max. Wall Thickness [mm]","Maks. Et Kalınlığı [mm]"],
    ["Projected Area [sqmm]","İzdüşüm Alanı [sqmm]"],
    ["Volume [ccm]","Hacim [ccm]"],
    ["No. of gates","Yolluk Giriş Sayısı"],
    ["Max. Flow Length [mm]","Maks. Akış uzunluğu [mm]"],
    ["Gate diameter [mm]","Yolluk Giriş Çapı [mm]"],
    ["Material","Malzeme"],
    ["Material type","Malzeme Türü"],
    ["MFR [g/10min.]","MFR"],
    ["Fibers / Fillers","Fiber / Katkı Malzemeleri"],
    ["Process Parameters","Proses Parametreleri"],
    ["Fill time [s]","Dolum Süresi [s]"],
    ["Melt temperature [C]","Eriyik Sıcaklığı [C]"],
    ["Mold temperature [C]","Kalıp sıcaklığı [C]"],
    ["Clamp force [t]","Kapama Kuvveti [t]"],
    ["Injection pressure [bar]","Enjeksiyon basıncı [Bar]"],
    ["Packing pressure [bar]","Tutma Basıncı [Bar]"],
    ["Packing time [s]","Tutma Zamanı [s]"],
    ["Cooling time [s]","Soğuma Süresi [s]"],
    ["Rest cycle time [s]","Kalan Çevrim Süresi [s]"],
    ["Min. Wall Thickness [mm]","Min. Et Kalınlığı [mm]"],
    ["Avg. Wall Thickness [mm]","Ort. Et Kalınlığı [mm]"],
    ["Max. Wall Thickness [mm]","Maks. Et Kalınlığı [mm]"],
    ["Projected Area [sqmm]","İzdüşüm Alanı [sqmm]"],
    ["Volume [ccm]","Hacim [ccm]"],
    ["No. of gates","Yolluk Giriş Sayısı"],
    ["Max. Flow Length [mm]","Maks. Akış uzunluğu [mm]"],
    ["Gate diameter [mm]","Yolluk Giriş Çapı [mm]"],
    ["Material type","Malzeme Türü"],
    ["MFR [g/10min.]","MFR [g/10min.]"],
    ["Fibers / Fillers","Fiber / Katkı Malzemeleri"],
    ["E-Mail","E-Posta"],
    ["Beta access key","Beta erişim şifresi"],
    ["CSV","CSV"],
    ["Array (User Input)","Dizi (kullanıcı girişi)"],
    ["Language","Dilim"],
    ["I agree to the ","Katılıyorum"],
    ["Data Privacy (Policy) (EN)","Veri Gizliliği (Politika) (EN)"],
    ["(General) Terms and Conditions (EN)","(Genel) Şartlar ve Koşullar (EN)"],
    ["and","ve"],
    ["To report bugs, give a feedback or comment on and vote for other users' feedback, visit ","Hataları bildirmek için geri bildirimde bulunun veya yorum yapın ve diğer kullanıcıların geri bildirimlerine oy verin, "],
    ["mustermind.convas.io","MUSTERNIND.CONVAS.IO"],
    [".","yu ziyaret edin."],
    ];
    for (var i = 0; i < 78; i++) {
    document.getElementById("text"+(i+1)).innerHTML = TextArr[i][language]
    };
    }
